---
title: "Emergency Brussels Sprouts"
type: "challenge"
description: "Implementing classes with composition"
tags: "oop, object-composition"
visibility: "assign"
ignore:
- "emergency-brussels-sprouts.md"
